plugins { id 'com.android.application' }

android {
    namespace 'com.tawjeeh.app'
    compileSdk 36

    defaultConfig {
        applicationId 'com.tawjeeh.app'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug { minifyEnabled false }
    }
}
